### ISSUE TITLE
FBSDKShareKit v6.3.0 is failing to build using Cocoapods

### ISSUE THREAD

**Issue by TRIMER** [facebook/facebook-ios-sdk#1302] opened 2020-03-30 14:08 UTC
## Environment

- Xcode Version: `11.4`
- Objective-C
- Installation Platform & Verison: `Cocoapods` version `1.8.4`

## Problem

Can't compile project with FBSDKShareKit v6.3.0.

## Steps to Reproduce & Details

My podspec file fragment:

```
...
spec.dependency 'FBSDKShareKit', '~> 6.0'
...
```

My Podfile file fragment:
```
...
pod 'MyPod'
...
```

Intall pods:

```
... % pod install
Analyzing dependencies
Downloading dependencies
Installing FBSDKCoreKit (6.3.0)
Installing FBSDKShareKit (6.3.0)
...
```

Run project and getting error:
/.../Pods/Headers/Public/FBSDKShareKit/FBSDKShareKit/FBSDKCoreKitImport.h:29:9: Module 'FBSDKCoreKit' not found

<img width="697" alt="Screenshot 2020-03-30 at 17 53 03" src="https://user-images.githubusercontent.com/1477997/77920569-b3d2c780-72af-11ea-839b-6cdf6b27b50f.png">

Error on line 29 `@import FBSDKCoreKit;` Looks like `FBSDKCOCOAPODS` undefined.

`FBSDKCOCOAPODS` defined in two podspecs:
1) https://github.com/CocoaPods/Specs/blob/master/Specs/9/b/5/FBSDKCoreKit/6.3.0/FBSDKCoreKit.podspec.json
`FBSDKCOCOAPODS` defined in sections `pod_target_xcconfig` and `user_target_xcconfig`.
2) https://github.com/CocoaPods/Specs/blob/master/Specs/c/a/b/FBSDKShareKit/6.3.0/FBSDKShareKit.podspec.json
`FBSDKCOCOAPODS` defined in section `prefix_header_contents`. 

It seems to me that definition of `FBSDKCOCOAPODS` in  `prefix_header_contents` is wrong. If I edit FBSDKShareKit.podspec.json and define `FBSDKCOCOAPODS`  in `pod_target_xcconfig` (like in FBSDKCoreKit.podspec.json) then project is building correctly.

Please review FBSDKShareKit.podspec.json

**Comment by joesus** [comment] 2020-03-30 18:13
>https://github.com/CocoaPods/Specs/blob/master/Specs/9/b/5/FBSDKCoreKit/6.3.0/FBSDKCoreKit.podspec.json
FBSDKCOCOAPODS defined in sections pod_target_xcconfig and user_target_xcconfig.

Since FBSDKShareKit has a direct dependency on FBSDKCoreKit the definition should exist... how are you importing FBSDKShareKit in your sourcefiles?

Are you able to provide a minimal reproducible sample?

**Comment by TRIMER** [comment] 2020-03-31 06:28
It's be difficult because pod from private repository.

MyPod.podspec:
```
Pod::Spec.new do |spec|
  spec.name = 'MyPod'
  spec.version = '3.4.7'
  spec.source = ...
  spec.summary = '...'
  spec.license = '...'
  spec.homepage = '...'
  spec.author = '...'
  
  spec.platform = :ios
  spec.ios.deployment_target = '9.0'
  spec.requires_arc = true

  spec.source_files = '...'
  spec.preserve_path = '...'
  spec.framework = 'MessageUI'
  spec.weak_framework = 'Social'

  spec.dependency 'FBSDKShareKit', '~> 6.0'
  spec.dependency 'VK-ios-sdk', '~> 1.0'
  spec.dependency 'TwitterKit', '~> 3.0'
end
```

Source code of MyPod import Facebook like this:
```
#import <Foundation/Foundation.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKShareKit/FBSDKShareKit.h>

@interface ...
```

Podfile from sample project: 
```
source 'https://github.com/CocoaPods/Specs.git'
source '...'

platform :ios, '9.0'

project 'FacebookCocoapods'

def shared_pods
  pod 'MyPod'
end

target 'FacebookCocoapods' do
    shared_pods
end
```

Run `pod install`. Trying compile project cause error: 
/.../Pods/Headers/Public/FBSDKShareKit/FBSDKShareKit/FBSDKCoreKitImport.h:29:9: Module 'FBSDKCoreKit' not found

Bug reproduces only if I using FBSDKShareKit as MyPod dependency. In case of use FBSDKShareKit directly in Podfile then importing headers are working without errors. And one more moment. If I define `FBSDKCOCOAPODS` manualy in my podspec then bug is gone. Like this (see end of spec):
```
Pod::Spec.new do |spec|
  spec.name = 'MyPod'
  spec.version = '3.4.7'
  spec.source = ...
  spec.summary = '...'
  spec.license = '...'
  spec.homepage = '...'
  spec.author = '...'
  
  spec.platform = :ios
  spec.ios.deployment_target = '9.0'
  spec.requires_arc = true

  spec.source_files = '...'
  spec.preserve_path = '...'
  spec.framework = 'MessageUI'
  spec.weak_framework = 'Social'

  spec.dependency 'FBSDKShareKit', '~> 6.0'
  spec.dependency 'VK-ios-sdk', '~> 1.0'
  spec.dependency 'TwitterKit', '~> 3.0'

  spec.pod_target_xcconfig = { 'GCC_PREPROCESSOR_DEFINITIONS' => 'FBSDKCOCOAPODS=1' }
end
```

**Comment by KAMIKAZEUA** [comment] 2020-04-06 21:40
Same here and even with manual install. I'm using C++ project. Did not update the project for 8 months... 
Previous version of ShareKit worked well.
Fixing manually import to:

```
#if defined BUCK
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#elif defined __cplusplus
**#import <FBSDKCoreKit/FBSDKCoreKit.h>**  //----- fix
```

fixes this issue, but then I got a bunch of errors:

> Undefined symbols for architecture arm64:
  "_FBSDKAppEventsDialogShareModeNative", referenced from:
      l_switch.table.NSStringFromFBSDKShareDialogMode in FBSDKShareKit(FBSDKShareDialogMode.o)
  "_FBSDKAppEventsDialogShareModeUnknown", referenced from:
      _NSStringFromFBSDKShareDialogMode in FBSDKShareKit(FBSDKShareDialogMode.o)
  "_FBSDKAppEventParameterDialogShareContentUUID", referenced from:
      -[FBSDKMessageDialog _logDialogShow] in FBSDKShareKit(FBSDKMessageDialog.o)
  "_FBSDKAppEventNameFBSDKEventMessengerShareDialogResult", referenced from:
      -[FBSDKMessageDialog _invokeDelegateDidCancel] in FBSDKShareKit(FBSDKMessageDialog.o)

And 100+ more like these.

**Comment by joesus** [comment] 2020-04-07 01:41
@KAMIKAZEUA, are you able to provide a small sample project that reproduces this issue? I was not able to reproduce locally. Thanks!

**Comment by KAMIKAZEUA** [comment] 2020-04-07 09:30
This is too tuff. I have a very old project using cocos2d-x and I can't share it, also I can't just create a sample. This is all legacy and really complicated. Even if I can spent a couple of days to make it work.. it would be like 500mb sample project with all libraries. 

Anyway looks like Undefined symbols for architecture arm64 is due to I haven't imported some Framework in the Xcode. Any ideas of what it is? 

p.s. FBSDKShareKit.framework/Headers/FBSDKShareDialogMode.h:   @Displays the dialog in a UIWebView within the app. - is this SDK still not fixed this?

**Comment by joesus** [comment] 2020-04-07 16:34
> p.s. FBSDKShareKit.framework/Headers/FBSDKShareDialogMode.h: @DISPLAYS the dialog in a UIWebView within the app. - is this SDK still not fixed this?

FBSDKWebDialogView uses a WKWebview.


@TRIMER, I think this issue can be resolved by adding an additional dependency on `FBSDKCoreKit`. Please comment if that does not work and we can revisit this. Closing for now.

**Closed by joesus** 2020-04-07 16:34 UTC
