### ISSUE TITLE
FBSDKCoreKIt.modulemap file not found

### ISSUE THREAD

**Issue by MusemoDeveloper** [facebook/facebook-ios-sdk#1423] opened 2020-07-08 08:38 UTC
## Checklist
Hello, I am getting this issue :FBSDKCoreKIt.modulemap file not found, in xCode project with empty project
I am using
Unity 2019.2
FB SDK for Unity v7.21.1
If I am using workspace I am getting 100 issues

How can we fix that?

**Comment by joesus** [comment] 2020-07-09 16:44
I believe this issue is being addressed in the Unity SDK repo.

https://github.com/facebook/facebook-sdk-for-unity/issues/450

**Closed by joesus** 2020-07-09 16:44 UTC

**Comment by luke-boniface** [comment] 2020-07-24 16:54
FB SDK for Unity v7.21.1
Unity 2018.4.19f1
XCode 11.3

We manually applied the [patch](https://github.com/facebook/facebook-sdk-for-unity/commit/8fdb57a76d2f5a14c168e91663280d40f274c74c) that is soon to be officially released mentioned in the above thread (facebook/facebook-sdk-for-unity#450). 

We verified the generated xcode project has these settings applied and the additional swift file added, but we're still unfortunately getting the FBSDKCoreKit.modulemap file not found issue mentioned above.

Any ideas?

`CompileSwift normal armv7 OUR_UNITY_BUILD_DIR/iOS-workspace/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/Swift/Enums+Extensions.swift (in target 'FBSDKShareKit' from project 'Pods')
    cd OUR_UNITY_BUILD_DIR/iOS-workspace/Pods
    /Applications/Xcode_11.3/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -emit-bc OUR_UNITY_BUILD_DIR/iOS-workspace/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/Swift/Enums+Extensions.swift -emit-module-path /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/Objects-normal/armv7/FBSDKShareKit.swiftmodule -emit-module-doc-path /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/Objects-normal/armv7/FBSDKShareKit.swiftdoc -serialize-diagnostics-path /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/Objects-normal/armv7/FBSDKShareKit-master.dia -emit-objc-header-path /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/Objects-normal/armv7/FBSDKShareKit-Swift.h -emit-dependencies-path /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/Objects-normal/armv7/FBSDKShareKit-master.d -target armv7-apple-ios8.0 -enable-objc-interop -sdk /Applications/Xcode_11.3/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -I OUR_UNITY_BUILD_DIR/iOS-release -I /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FBSDKCoreKit -F OUR_UNITY_BUILD_DIR/iOS-release -g -import-underlying-module -module-cache-path /Users/our_user/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -O -D COCOAPODS -serialize-debugging-options -Xcc -working-directory -Xcc OUR_UNITY_BUILD_DIR/iOS-workspace/Pods -Xcc -fmodule-map-file=/Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FBSDKCoreKit/FBSDKCoreKit.modulemap -Xcc -fmodule-map-file=OUR_UNITY_BUILD_DIR/iOS-workspace/Pods/Headers/Public/FBSDKShareKit/FBSDKShareKit.modulemap -Xcc -I/Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/FBSDKShareKit-generated-files.hmap -Xcc -I/Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/FBSDKShareKit-own-target-headers.hmap -Xcc -I/Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/FBSDKShareKit-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/FBSDKShareKit-project-headers.hmap -Xcc -IOUR_UNITY_BUILD_DIR/iOS-release/include -Xcc -IOUR_UNITY_BUILD_DIR/iOS-workspace/Pods/Headers/Private -Xcc -IOUR_UNITY_BUILD_DIR/iOS-workspace/Pods/Headers/Private/FBSDKShareKit -Xcc -IOUR_UNITY_BUILD_DIR/iOS-workspace/Pods/Headers/Public -Xcc -IOUR_UNITY_BUILD_DIR/iOS-workspace/Pods/Headers/Public/FBSDKShareKit -Xcc -I/Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/DerivedSources-normal/armv7 -Xcc -I/Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/DerivedSources/armv7 -Xcc -I/Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/DerivedSources -Xcc -DPOD_CONFIGURATION_RELEASE=1 -Xcc -DCOCOAPODS=1 -parse-as-library -module-name FBSDKShareKit -num-threads 12 -o /Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBSDKShareKit.build/Objects-normal/armv7/Enums+Extensions.bc
<unknown>:0: error: module map file '/Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FBSDKCoreKit/FBSDKCoreKit.modulemap' not found
<unknown>:0: error: module map file '/Users/our_user/Library/Developer/Xcode/DerivedData/Unity-iPhone-ddmovjestcmtnadlxpozjwqziahw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FBSDKCoreKit/FBSDKCoreKit.modulemap' not found
<unknown>:0: error: missing required module 'SwiftShims'`

**Comment by belgamo** [comment] 2020-07-28 21:55
I have the same error...

**Comment by SeveneduS** [comment] 2020-08-09 09:02
Exactly the same issue. Unity 2019.4.7f1 and 209.3.15f1

**Comment by feraligatr** [comment] 2020-08-19 10:37
I think this error is caused by building from "xcodeproj" file instead of "xcworkspace" file. So pods are not compiled at all.

**Comment by johnatzark** [comment] 2020-10-23 17:47
For me it was the same mentioned by @feraligatr 
I was opening the project file instead of the workspace file.
