### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FBSDKCoreKit/Basics"

### ISSUE THREAD

**Issue by Jdb156158** [facebook/facebook-ios-sdk#1633] opened 2021-02-03 10:08 UTC
# foacebook广告
  pod 'FBAudienceNetwork', '~> 6.2.1'
  # foacebook统计
  pod 'FacebookCore', '~> 0.9.0'

我们想在这两个sdk中都使用最新的版本，但是它们不兼容：
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit/Basics":
  In snapshot (Podfile.lock):
    FBSDKCoreKit/Basics (= 5.15.1)

  In Podfile:
    FBAudienceNetwork (~> 6.2.1) was resolved to 6.2.1, which depends on
      FBSDKCoreKit/Basics (>= 7.0.1)

Specs satisfying the `FBSDKCoreKit/Basics (= 5.15.1), FBSDKCoreKit/Basics (>= 7.0.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by joesus** [comment] 2021-02-03 15:46
What is the deployment target for your project?

**Comment by Jdb156158** [comment] 2021-02-05 13:06
因为我们接入的第三方广告需要FBAudienceNetwork为最新的6.2.1版本，但是我们还需要接入统计功能FacebookCore的最近几个版本所依赖的FBSDKCoreKit都比较低，所以出现了这个不兼容的问题。

**Comment by joesus** [comment] 2021-02-05 17:06
Seems like this is a possible duplicate of #1621 
Please use that to track the issue.

**Closed by joesus** 2021-02-05 17:06 UTC
Labels: enhancement

**Comment by MarcoLavoro** [comment] 2021-09-04 10:43
Same problem using the LAST VERSIONS OF SDK!
