### ISSUE TITLE
-[NSNull count]: unrecognized selector sent to instance 0x22d0ed7f0

### ISSUE THREAD

**Issue by Neil20170223** [facebook/facebook-ios-sdk#1430] opened 2020-07-10 10:37 UTC
SDK version: iOS 6.5.2

<img width="1468" alt="图片" src="https://user-images.githubusercontent.com/28893316/87146006-e04da500-c2dc-11ea-95ad-f0f75b73ea64.png">

**Comment by Neil20170223** [comment] 2020-07-10 10:38
Please help

**Comment by ferico55** [comment] 2020-07-10 10:40
![Screen Shot 2020-07-10 at 17 37 06](https://user-images.githubusercontent.com/7204143/87145972-6fa28a80-c2d4-11ea-9ccb-f453ee521dfa.png)

here's better stack trace

**Comment by artyom-stv** [comment] 2020-07-10 10:42
<img width="1234" alt="Screenshot 2020-07-10 at 13 42 31" src="https://user-images.githubusercontent.com/2537357/87146194-3c033880-c2b3-11ea-8dd3-db6ef4e07eea.png">

**Comment by barisyazganc** [comment] 2020-07-10 10:45
Same here! shame on you FB!! what should we do now? just wait for them to release their mistake and rollback?

**Comment by shengyang998** [comment] 2020-07-10 10:48
#1374

**Comment by vladambartsumyan** [comment] 2020-07-10 10:48
same here 
    pod 'FBSDKCoreKit', '5.5.0'
    pod 'FBSDKShareKit', '5.5.0'
    pod 'FBSDKLoginKit', '5.5.0'

**Comment by danwey** [comment] 2020-07-10 10:50
same here
6.3.0 and 5.0.2

**Comment by georgescumihai** [comment] 2020-07-10 10:50
Version 7.0 same issue

**Comment by TheyCallMeTank** [comment] 2020-07-10 10:51
same
  pod 'FBSDKCoreKit', '5.8.0'
  pod 'FBSDKLoginKit', '5.8.0'
  pod 'FBSDKShareKit', '5.8.0'

**Comment by jolyot** [comment] 2020-07-10 10:51
same here
```
Using FBSDKCoreKit (5.13.1)
Using FBSDKLoginKit (5.13.1)
```

**Comment by yaminoma** [comment] 2020-07-10 10:51
Same Issue
When will it be fixed?

**Comment by olenhad** [comment] 2020-07-10 10:52
Same issue here with 5.5.0

**Comment by racer1988** [comment] 2020-07-10 10:52
+1

**Comment by zavsby** [comment] 2020-07-10 10:54
Same here, more then 500K of crashes for only last 20 minutes...

**Comment by Sanich63** [comment] 2020-07-10 10:54
<img width="1551" alt="Screenshot 2020-07-10 at 14 54 12" src="https://user-images.githubusercontent.com/2470438/87147189-3f9bbd00-c2bd-11ea-97cc-979ab54ded19.png">

**Comment by acali18** [comment] 2020-07-10 10:58
Same issue, right where @Sanich63 shows on the screenshot

**Comment by fireup** [comment] 2020-07-10 10:58
OH COME ON! Not again! Your crash has halted Firebase crashlytics again!

**Comment by DarrenDuXuan** [comment] 2020-07-10 10:58
![image](https://user-images.githubusercontent.com/15886912/87147511-4fc49400-c2df-11ea-9c05-b9424160704b.png)
restrictive_data_filter_params NSNull.count

**Comment by jonashinge** [comment] 2020-07-10 10:59
same here using `7.0.0`.

**Comment by hemantfreenow** [comment] 2020-07-10 10:59
+1

**Comment by davidchristiandy** [comment] 2020-07-10 10:59
I'm suspecting that this might be a backend related issue from FB side, because crash happens on app released a month ago.  Maybe some wrong values gets sent from their feature flag server or something, and causes crash on the client. 

Hope FB can roll back whatever changes quickly.

**Comment by magnett** [comment] 2020-07-10 11:00
7.0.0 is crashing, 7.1.1 seems stable

**Comment by hemanthmpkumar** [comment] 2020-07-10 11:00
+1

**Comment by abuharsky** [comment] 2020-07-10 11:00
+1 crashing

**Comment by Balashov152** [comment] 2020-07-10 11:01
+1 crashing

**Comment by Tomoy** [comment] 2020-07-10 11:03
Oh god, this is happening again, crashing to all my users

**Comment by darlanxw** [comment] 2020-07-10 11:03
+1 crashing

**Comment by sahmzheii** [comment] 2020-07-10 11:03
+1 crashing

**Comment by zavsby** [comment] 2020-07-10 11:04
Seems it's night in US and no one react from FB...

**Comment by Mehul1437** [comment] 2020-07-10 11:05
Same here +1 crashing

**Comment by Subloran** [comment] 2020-07-10 11:06
Also crashes [FBSDKRestrictiveDataFilterManager updateFilters:] + 62. There is a check for restrictiveParams.count, but restrictiveParams is NSNull object.

**Comment by peterdk** [comment] 2020-07-10 11:06
Same

**Comment by Tomoy** [comment] 2020-07-10 11:06
fixed??

**Comment by Nackwork** [comment] 2020-07-10 11:07
Guys, our entire portfolio is crashing. Haven't you learned your lessons from May 7, 2020?

It's been 40min of total blackout and still no response?

I guess, we need more memes for FB QA department :)

**Comment by Mehul1437** [comment] 2020-07-10 11:07
#4	0x00000001052ff274 in +[FBSDKRestrictiveDataFilterManager updateFilters:] at /Users/travis/build/facebook/facebook-objc-sdk/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/FBSDKRestrictiveDataFilterManager.m:60

**Comment by ivaneChen** [comment] 2020-07-10 11:07
我也是～中招了

**Comment by Tomoy** [comment] 2020-07-10 11:08
> fixed??

Its randomly working and crashing for me

**Comment by ivaneChen** [comment] 2020-07-10 11:08
Same here +1 crashing

**Comment by charlieInDen** [comment] 2020-07-10 11:08
Seriously - Start removing this SDK soon!!

**Comment by danwey** [comment] 2020-07-10 11:08
别说中文。professional.

**Comment by PavloNovak** [comment] 2020-07-10 11:08
This issue has 12413 crashes affecting 5821 users =(

**Comment by dave7280** [comment] 2020-07-10 11:08
That's how it ends how 3/4 of application rely on single sdk from one vendor. 
You can only blame yourself.

**Comment by ivaneChen** [comment] 2020-07-10 11:08
別說簡體字

**Comment by fireup** [comment] 2020-07-10 11:10
> Guys, our entire portfolio is crashing! Haven't you learned your lessons from May 7, 2020?
> 
> It's been 40min of total blackout and still no response?
> 
> I guess, we need more memes for FB QA department :)

Apparently they fired the wrong guy in May.

**Comment by mzying2013** [comment] 2020-07-10 11:10
6.5.1  crash, please help!

**Comment by mweststrate** [comment] 2020-07-10 11:10
Linking for visibility: https://developers.facebook.com/status/issues/1739188102911114/

**Comment by batuhanaltun** [comment] 2020-07-10 11:10
jh doeqwdwdhıou hewoıdwddoıewho ıofwdwdehwf ejf eıj ıfeıq jıdfj ıejd ıej ıfje jıfej ıeıf ceqjdı w0ıd ıw0 jq0dı jw0

I couldn't find a word to describe this event that happened 2 times in a short time.

**Comment by sunflash** [comment] 2020-07-10 11:13
please fix ASAP

**Comment by burcsade** [comment] 2020-07-10 11:13
unbelievable... second time this year.

**Comment by racer1988** [comment] 2020-07-10 11:14
@Neil20170223 Please EDIT the issue with the status link: https://developers.facebook.com/status/issues/1739188102911114/

**Comment by JZWDream** [comment] 2020-07-10 11:15
6.5.0,please help

**Comment by nicoyuste** [comment] 2020-07-10 11:16
Groupon app is crashing on startup due to the same issue.

**Comment by mskalgorepublic** [comment] 2020-07-10 11:18
They are responding at last. 
<img width="743" alt="Screenshot 2020-07-10 at 4 17 34 PM" src="https://user-images.githubusercontent.com/45307265/87149018-e9347b80-c2c8-11ea-86c6-bf44240e37a5.png">

**Comment by oliver98844** [comment] 2020-07-10 11:18
Same in our app...cannot open Spotify, either 😱

**Comment by absolute-heike** [comment] 2020-07-10 11:20
🤦‍♀️  Looks like facebook hired a lot of Swift engineers in the last time and let them do stuff to the networking code 😂

**Comment by hongdangodori** [comment] 2020-07-10 11:20
Same in our app... plz help..

**Comment by NutnichaP** [comment] 2020-07-10 11:20
Does anyone try to degrade its version?

**Comment by vdugnist** [comment] 2020-07-10 11:22
same, FBSDKLoginKit 5.6.0

**Comment by Salman144017** [comment] 2020-07-10 11:23
It has started working now. I believe they reverted the change.

**Comment by Tomoy** [comment] 2020-07-10 11:24
> It has started working now. I believe they reverted the change.

still crashing here

**Comment by Geeks2020** [comment] 2020-07-10 11:25
haha I am not facing this alone. It is working for now

**Comment by nicoyuste** [comment] 2020-07-10 11:25
> It has started working now. I believe they reverted the change.

Not for me. I still see Groupon, Spotify, Strava, Wallapop apps crashing...

**Comment by vijay0964** [comment] 2020-07-10 11:27
Not crashing in 7.1.1 version.

**Comment by patrikqvarnstrom** [comment] 2020-07-10 11:28
This is the new thanks, Obama meme. 

Thanks, Facebook!

**Comment by ankitatdelhii** [comment] 2020-07-10 11:31
Seems like everyone is facing this issue. Thank God! I am not alone.😭

**Comment by Sanich63** [comment] 2020-07-10 11:31
Just keep it here...
![SM-MSgWe-DE](https://user-images.githubusercontent.com/2470438/87150002-51339380-c2c2-11ea-9250-d052bee56747.jpg)

**Comment by nicoyuste** [comment] 2020-07-10 11:33
Stack trace I see when I open my app:
```
2020-07-10 13:20:10.002959+0200 XXX[65519:1877435] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull count]: unrecognized selector sent to instance 0x7fff80618070'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c91fd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c75c4c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c77f78 _CF_forwarding_prep_0 + 120
	5   Groupon                             0x000000010bc79f2d +[FBSDKRestrictiveDataFilterManager updateFilters:] + 109
	6   Groupon                             0x000000010bc7f4d1 +[FBSDKServerConfigurationManager processLoadRequestResponse:error:appID:] + 3665
	7   Groupon                             0x000000010bc61a7f __69+[FBSDKGraphRequestPiggybackManager addServerConfigurationPiggyback:]_block_invoke + 175
	8   Groupon                             0x000000010bc5f208 -[FBSDKGraphRequestMetadata invokeCompletionHandlerForConnection:withResults:error:] + 248
	9   Groupon                             0x000000010bc5a8db __82-[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:]_block_invoke + 251
	10  Groupon                             0x000000010bc5a6fd -[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:] + 1149
	11  Groupon                             0x000000010bc5a1e6 __64-[FBSDKGraphRequestConnection completeWithResults:networkError:]_block_invoke + 1494
	12  CoreFoundation                      0x00007fff23c3f1e7 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	13  CoreFoundation                      0x00007fff23b847d4 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 228
	14  Groupon                             0x000000010bc59a9e -[FBSDKGraphRequestConnection completeWithResults:networkError:] + 1102
	15  Groupon                             0x000000010bc584e0 -[FBSDKGraphRequestConnection completeFBSDKURLSessionWithResponse:data:networkError:] + 2336
	16  Groupon                             0x000000010bc54b1a __36-[FBSDKGraphRequestConnection start]_block_invoke_3 + 186
	17  Groupon                             0x000000010bc5ca66 __73-[FBSDKGraphRequestConnection invokeHandler:error:response:responseData:]_block_invoke + 70
	18  libdispatch.dylib                   0x000000011c4e9dd4 _dispatch_call_block_and_release + 12
	19  libdispatch.dylib                   0x000000011c4ead48 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000011c4f8de6 _dispatch_main_queue_callback_4CF + 1500
	21  CoreFoundation                      0x00007fff23bd4049 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x00007fff23bceca9 __CFRunLoopRun + 2329
	23  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	24  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	25  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	26  Groupon                             0x000000010916da20 main + 1296
	27  libdyld.dylib                       0x00007fff5227ec25 start + 1
	28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by Kalzem** [comment] 2020-07-10 11:34
Can Facebook learn from their mistake and have a proper QA instead of making crash all iOS apps using their SDK?

**Comment by PetrBodnar** [comment] 2020-07-10 11:38
Our apps can start again

**Comment by nshtg** [comment] 2020-07-10 11:38
Solution: We won't use FB SDK in the future. Thank you Mark suckerberg.

**Comment by ltk-daniel-zapater** [comment] 2020-07-10 11:40
Wallapop working again, Spotify still crashing

**Comment by danglingP0inter** [comment] 2020-07-10 11:42
So Fb developers also test their changes at prod. I'm so glad that I'm not alone.

**Comment by vrutberg** [comment] 2020-07-10 11:44
FWIW I'm also getting this crash right now

**Comment by apogodin** [comment] 2020-07-10 11:46
Temporary fix while developing

@interface NSNull (Fix)
- (NSUInteger)count;
@end
...
@implementation NSNull (Fix)
- (NSUInteger)count
{
    return 0;
}
@end

**Comment by jasondinh** [comment] 2020-07-10 11:47
Permanent fix in dev and production

1. Remove FB SDK
2. ???
3. Profit

**Comment by vlmxs** [comment] 2020-07-10 11:47
May this be the reason PUBG Mobile is not working on my iPad?

**Comment by Geeks2020** [comment] 2020-07-10 11:48
> Permanent fix in dev and production
> 
> 1. Remove FB SDK
> 2. ???
> 3. Profit

haha do we have a choice?

**Comment by nicoyuste** [comment] 2020-07-10 11:49
You are not alone: https://downdetector.com

**Comment by DouglasMarq** [comment] 2020-07-10 11:51
Stop blaming entirely at Facebook, your app is crashing because it is relying entirely at a 3rd party SDK..

**Comment by UnknownNPC** [comment] 2020-07-10 11:51
Friday deployment went fine.

**Comment by Salman144017** [comment] 2020-07-10 11:52
> Stop blaming entirely at Facebook, your app is crashing because it is relying entirely at a 3rd party SDK..

So it's wrong to allow social login in your app?

**Comment by burcsade** [comment] 2020-07-10 11:53
Fail fast, fail everyone

**Comment by iBodia** [comment] 2020-07-10 11:53
same here

Using FBSDKCoreKit (6.3.0)
Using FBSDKLoginKit (6.3.0)

**Comment by skibitsky** [comment] 2020-07-10 11:53
> So it's wrong to allow social login in your app?

Now we learned that it's wrong :)

**Comment by DouglasMarq** [comment] 2020-07-10 11:54
> So it's wrong to allow social login in your app?

It's not wrong to allow social login at your app, it is wrong to rely your app at a SDK, you can handle this in another way, through cache or temporary data to make calls later.

**Comment by Cool04ek** [comment] 2020-07-10 11:54
Same here 5.2.3

**Comment by ckcharchit** [comment] 2020-07-10 11:56
> May this be the reason PUBG Mobile is not working on my iPad?
> 
> Yes, and Spotify as well...

Yes, Call of Duty Mobile, ludo star, as well.

**Comment by sandeepbol** [comment] 2020-07-10 11:56
@DouglasMarq From where do you buy weed mate? 🚬

**Comment by Salman144017** [comment] 2020-07-10 11:57
> > So it's wrong to allow social login in your app?
> 
> It's not wrong to allow social login at your app, it is wrong to rely your app at a SDK, you can handle this in another way, through cache or temporary data to make calls later.
> 
> Edit: Oh damn facebook sdk having issues, my app is not working, i'll just blame at it and wait for a result.

Read your comment again and let me know if you find any sense in it.

**Comment by apisdk** [comment] 2020-07-10 12:00
🤦‍♂️ ...

**Comment by BrianValente** [comment] 2020-07-10 12:00
> > So it's wrong to allow social login in your app?
> 
> It's not wrong to allow social login at your app, it is wrong to rely your app at a SDK, you can handle this in another way, through cache or temporary data to make calls later.
> 
> Edit: Oh damn facebook sdk having issues, my app is not working, i'll just blame at it and wait for a result.

Did you even made an iOS app?

**Comment by revolter** [comment] 2020-07-10 12:01
Isn't Facebook using this SDK? How could they not notice that it crashes? You don't need extensive tests. Simply open the app. 🤦🏻‍♂️

**Comment by 1Podoshva** [comment] 2020-07-10 12:02
The same issue. 
My app crashes only on a simulator, for a device the app does not crash(log in via FB works fine).
In a device and simulator, the object of **events** is **NSNull** class type.

<img width="644" alt="Screenshot 2020-07-10 at 14 56 03" src="https://user-images.githubusercontent.com/8791605/87152329-2ba48b00-c2be-11ea-8337-9aca2440a4ec.png">

**Comment by RuiAAPeres** [comment] 2020-07-10 12:03
Facebook, WhatsApp, Instagram and FB's Messenger are working. 

![](https://media.giphy.com/media/Vsl4fGedmYFRC/giphy.gif)

**Comment by apolegoshko** [comment] 2020-07-10 12:03
![image](https://user-images.githubusercontent.com/19555411/87152477-0f9ceb80-c2b6-11ea-99da-60faa6a441b6.png)

**Comment by beretis** [comment] 2020-07-10 12:03
> > So it's wrong to allow social login in your app?
> 
> It's not wrong to allow social login at your app, it is wrong to rely your app at a SDK, you can handle this in another way, through cache or temporary data to make calls later.
> 
> Edit: Oh damn facebook sdk having issues, my app is not working, i'll just blame at it and wait for a result.

Dude, even if I comment out import of the sdk, its still crashing. I have to remove SDK, now tell me about that. Im not rallying of SDK, facebook login is just a feature.

**Comment by skibitsky** [comment] 2020-07-10 12:04
I can confirm that the issue was resolved for my app

**Comment by dave7280** [comment] 2020-07-10 12:04
> > > So it's wrong to allow social login in your app?
> > 
> > 
> > It's not wrong to allow social login at your app, it is wrong to rely your app at a SDK, you can handle this in another way, through cache or temporary data to make calls later.
> > Edit: Oh damn facebook sdk having issues, my app is not working, i'll just blame at it and wait for a result.
> 
> Did you even made an iOS app?

He's completely right, but plenty of developers have problems understanding business.

It's your job as developer to choose components you rely on, carefully. 
Everyone knew, that exactly same issue happened already before, yet people are very surprised that same problem is here again.

Your business client wont care if it's facebook fault. App is not working and that's it. 
It's developers decision to choose this SDK, you could use something else. 

Asses the risk on the components you use.

**Comment by Geeks2020** [comment] 2020-07-10 12:05
+1,  The issue is already fixed for my apps. I use FB login.

**Comment by revolter** [comment] 2020-07-10 12:06
> you could use something else

Like what?

**Comment by sandeepbol** [comment] 2020-07-10 12:08
> Facebook, WhatsApp, Instagram and FB's Messenger are working.
> 
> ![](https://camo.githubusercontent.com/6e534a6e45f7e84523ef3a692d46f8d5aec91da5/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f56736c34664765646d594652432f67697068792e676966)

Dude Facebook and Facebook messenger are React native apps and don't use this SDK.

**Comment by onursahindur** [comment] 2020-07-10 12:09
Same problem continues here also..

pod 'FBSDKCoreKit', '~> 5.0'
pod 'FBSDKShareKit', '~> 5.0'
pod 'FBAudienceNetwork', '~> 5.0'

Think the problem is in core.

![image](https://user-images.githubusercontent.com/5830807/87152998-63600280-c2bf-11ea-9087-2053c23adb9a.png)

**Comment by Magestro** [comment] 2020-07-10 12:16
https://twitter.com/elonmusk/status/1260852444818362369?lang=en

**Comment by demensdeum** [comment] 2020-07-10 12:21
@apogodin must be:
@interface NSNull (FacebookFix)

**Comment by hardW** [comment] 2020-07-10 12:24
For me updating FBSDKLoginKit and FBSDKShareKit to 5.15.1 (was 5.5.0) seem to fix an issue. Please double check.

**Comment by apogodin** [comment] 2020-07-10 12:26
> @apogodin must be:
> @interface NSNull (FacebookFix)

"FacebookFix" should be in investing in ObjC developers

**Comment by iliaprokhorov** [comment] 2020-07-10 12:28
@apogodin This case is raising warning in Swift

**Comment by sandeee1928** [comment] 2020-07-10 12:28
https://developers.facebook.com/support/bugs/329763701368293/

**Comment by Suvitruf** [comment] 2020-07-10 12:29
![2fb0e0593a6a0a07de957de7bf14fe3b](https://user-images.githubusercontent.com/1946939/87154579-29443000-c2c2-11ea-80bc-2f159288407a.jpg)

**Comment by zhuravel-sergey** [comment] 2020-07-10 12:30
pidary zaebali

**Comment by Salman144017** [comment] 2020-07-10 12:30
> For me updating FBSDKLoginKit and FBSDKShareKit to 5.15.1 (was 5.5.0) seem to fix an issue. Please double check.

I am using 5.15.1 and it was crashing initially but now its fixed for about half an hour ago.

**Comment by Ricowere** [comment] 2020-07-10 12:31
FB guys; The problem seems to be happening when a NSNull object is been passed by parameter... So nullable annotation here was not enough...

You will have to revisit all the library to add a if is instance of NSNull then return? 😄 

https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/EventDeactivation/FBSDKEventDeactivationManager.m#L71

https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/EventDeactivation/FBSDKEventDeactivationManager.m#L99

https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/EventDeactivation/FBSDKEventDeactivationManager.m#L112

**Comment by cruftyoldsysadmin** [comment] 2020-07-10 12:32
Using anything from Facebook is considered harmful to your business, unless you are Facebook.

**Comment by Salman144017** [comment] 2020-07-10 12:32
> > It has started working now. I believe they reverted the change.
> 
> still crashing here

I am using 5.15.1 and it was crashing initially but now its fixed for about half an hour ago. Try updating to 5.15.1.

**Comment by Salman144017** [comment] 2020-07-10 12:33
> It has started working now. I believe they reverted the change.

I am using 5.15.1 and it was crashing initially but now its fixed for about half an hour ago. Try updating to 5.15.1.

**Comment by hardW** [comment] 2020-07-10 12:34
> > For me updating FBSDKLoginKit and FBSDKShareKit to 5.15.1 (was 5.5.0) seem to fix an issue. Please double check.
> 
> I am using 5.15.1 and it was crashing initially but now its fixed for about half an hour ago.

If to switch back to 5.5.0 for me it crashes even now( So I guess there is fix that is working for 5.15.1 (or lower?) now.

**Comment by dyumin** [comment] 2020-07-10 12:36
> Temporary fix while developing
> 
> ```
> @interface NSNull (Fix)
> - (NSUInteger)count;
> @end
> ...
> @implementation NSNull (Fix)
> - (NSUInteger)count
> {
>     return 0;
> }
> @end
> ```

It's also possible to swizzle `updateFilters:` and call original implementation with empty NSDictionary in case NSNull is passed. Should do the trick for production hotfix.

**Comment by own2pwn** [comment] 2020-07-10 12:48
nu 4e zato O(n) mojem

**Comment by TheNamesJames** [comment] 2020-07-10 12:49
> This should do the trick for production hotfix


How quickly can your app be submitted, reviewed, approved and then have users update? Before FB issues a fix?
What a Race Condition! 🏎

> > Temporary fix while developing
> 
> > 
> 
> > ```
> 
> > @interface NSNull (Fix)
> 
> > - (NSUInteger)count;
> 
> > @end
> 
> > ...
> 
> > @implementation NSNull (Fix)
> 
> > - (NSUInteger)count
> 
> > {
> 
> >     return 0;
> 
> > }
> 
> > @end
> 
> > ```
> 
> 
> 
> It's also possible to swizzle `updateFilters:` and call original implementation with empty NSDictionary in case NSNull is passed. This should do the trick for production hotfix.

**Comment by diskman86** [comment] 2020-07-10 12:53
Seems Facebook fixed it. Can anyone confirm?

**Comment by alekseenkodev** [comment] 2020-07-10 12:54
> Seems Facebook fixed it. Can anyone confirm?

+

**Comment by chriscborg** [comment] 2020-07-10 12:57
yes fixed

**Comment by zavsby** [comment] 2020-07-10 12:59
yes, it's fixed now.

**Comment by varyP** [comment] 2020-07-10 13:38
Might not be crashing, but we are unable to verify token from our backend. Guess facebook has turned if off for a while.

**Comment by Mart-Bogdan** [comment] 2020-07-10 14:12
You should definitely RIIR to make it more memory-safe!

**Comment by joesus** [comment] 2020-07-10 15:47
Duplicate of #1427

**Closed by joesus** 2020-07-10 15:47 UTC

**Comment by mzying2013** [comment] 2020-07-11 03:24
我写了一个关于这个问题的文章，包含以后此类问题的预防方法： https://blog.mzying.com/index.php/archives/231/

**Comment by wangguan1** [comment] 2020-07-11 03:46
> 我写了一个关于这个问题的文章，包含以后此类问题的预防方法： https://blog.mzying.com/index.php/archives/231/

这个bug服了，OC里基本类型检查都没有
