### ISSUE TITLE
FB SDK Crashing at FBSDKRestrictiveDataFilterManager.m line 62 in [FBSDKRestrictiveDataFilterManager updateFilters:]

### ISSUE THREAD

**Issue by pandeypiyush** [facebook/facebook-ios-sdk#1440] opened 2020-07-13 01:19 UTC
Looks like issue#1432 is not fully resolved - Again seeing the FB SDK crash for some users starting at 6.35 AM EST.

<img width="869" alt="Screen Shot 2020-07-12 at 21 06 13" src="https://user-images.githubusercontent.com/5323234/87261336-d023fa00-c483-11ea-852f-f6a3decdff67.png">

0x0000000104e26240 +[FBSDKRestrictiveDataFilterManager updateFilters:] (FBSDKRestrictiveDataFilterManager.m:62)
6                        	 0x0000000104e1bbb8 +[FBSDKServerConfigurationManager processLoadRequestResponse:error:appID:] (FBSDKServerConfigurationManager.m:0)
7                        	 0x0000000104e19d04 __69+[FBSDKGraphRequestPiggybackManager addServerConfigurationPiggyback:]_block_invoke (FBSDKGraphRequestPiggybackManager.m:152)
8                        	 0x0000000104e7b520 -[FBSDKGraphRequestMetadata invokeCompletionHandlerForConnection:withResults:error:] (FBSDKGraphRequestMetadata.m:41)
9                        	 0x0000000104e89138 __82-[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:]_block_invoke (FBSDKGraphRequestConnection.m:799)
10                       	 0x0000000104e88f54 -[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:] (FBSDKGraphRequestConnection.m:834)
11                       	 0x0000000104e88b58 __64-[FBSDKGraphRequestConnection completeWithResults:networkError:]_block_invoke (FBSDKGraphRequestConnection.m:783)
12  CoreFoundation                 	 0x00000001aaf9267c __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ (CoreFoundation)
13  CoreFoundation                 	 0x00000001aae90248 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] (CoreFoundation)
14                       	 0x0000000104e885ac -[FBSDKGraphRequestConnection completeWithResults:networkError:] (FBSDKGraphRequestConnection.m:762)
15                       	 0x0000000104e87424 -[FBSDKGraphRequestConnection completeFBSDKURLSessionWithResponse:data:networkError:] (FBSDKGraphRequestConnection.m:627)
16                       	 0x0000000104e84308 __36-[FBSDKGraphRequestConnection start]_block_invoke_3 (FBSDKGraphRequestConnection.m:245)
17                       	 0x0000000104e8aeac __73-[FBSDKGraphRequestConnection invokeHandler:error:response:responseData:]_block_invoke (FBSDKGraphRequestConnection.m:985)

**Comment by ichina** [comment] 2020-07-13 12:38
same, we still receive those crashes

**Comment by BasilPP** [comment] 2020-07-13 13:35
Same, also receiving these, and crashes for "NSInvalidArgumentExceptionFBSDKEventDeactivationManager.m:64"

**Comment by tianqibt** [comment] 2020-07-13 15:39
Thanks for reporting! We checked the timestamp of crashes we received, and saw most of the crashes actually happened on July 10, but reached server much later, as the crash will only be sent when user restart the app. Also we have seen some invalid timestamps, which are later than the time when crash received by our server, because of users changed settings time. Would you guys please verify if your crashes are in the same cases as mentioned above? Thanks!

**Comment by pandeypiyush** [comment] 2020-07-13 16:14
@tianqibt thanks for looking into this! I spot checked a few crashes, and they all have session start timestamp from 07/10. So looks like the case you mentioned. We will keep monitoring.

**Comment by joesus** [comment] 2020-07-13 16:43
Duplicate of #1427

**Closed by joesus** 2020-07-13 16:43 UTC
