### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by fangshiqi-start** [facebook/facebook-ios-sdk#1893] opened 2021-09-22 01:37 UTC
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)

### Goals

When I log in with Facebook, when I open the Facebook login page in the app, it opens the Facebook app.When logging in in the Facebook app, he will open my app. But my application did not receive user information.

### Expected results

Facebook can log in normally.   In iPhone 11, iPhone X, iPhone 12, they all have this problem. The Facebook version is the lates

This is a video I recorded. Please check it。
https://user-images.githubusercontent.com/57080337/134269669-8b5f5b9f-b572-4252-a6ae-e3a8f00b8981.mp4

t.

### Code samples & details

```swift
FBSDKLoginManager *login = [[FBSDKLoginManager alloc] init];
        [login logInWithPermissions:@[@"public_profile"] fromViewController:self handler:^(FBSDKLoginManagerLoginResult * _Nullable result, NSError * _Nullable error) {
            if (error) {
              NSLog(@"Process error");
            } else if (result.isCancelled) {
              NSLog(@"Cancelled");
            } else {
              NSLog(@"Logged in");
            }
        }];
```

**Comment by jawwad** [comment] 2021-09-23 21:45
This is a duplicate of #1894. Closing this one.

**Closed by jawwad** 2021-09-23 21:45 UTC
Labels: enhancement
