### ISSUE TITLE
Used the SDK version of 5.0.2, and this afternoon suddenly caused a complete crash of the application

### ISSUE THREAD

**Issue by mrduank** [facebook/facebook-ios-sdk#1429] opened 2020-07-10 10:08 UTC
I used the SDK version of 5.0.2, and this afternoon suddenly caused a complete crash of the application

Crash information

-[NSNull count]: unrecognized selector sent to instance 0x1cd6fe1e0
2020-07-10 17:24:26.052924+0800 OSDemo[4198:604792] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull count]: unrecognized selector sent to instance 0x1cd6fe1e0'
*** First throw call stack:
(0x18b944300 0x18b658c1c 0x18b842a90 0x18b948a60 0x18b94ad60 0x102e3e8c4 0x102e36e0c 0x102e35a3c 0x102e73ee0 0x102e7cdc4 0x102e7cca8 0x102e7c858 0x18b91667c 0x18b814248 0x102e7c5fc 0x102e7b948 0x102e79930 0x103471d10 0x10347318c 0x103481d14 0x18b8bf6b0 0x18b8ba2c8 0x18b8b98f4 0x195cd0604 0x18fa8d358 0x102a3f1a4 0x18b7352dc)
libc++abi.dylib: terminating with uncaught exception of type NSException

Hope you help me solve this problem as soon as possible, thank you very much！

**Comment by mskalgorepublic** [comment] 2020-07-10 10:16
I have faced the same issue and this causes crash on launch up.
Its crashing after **completionHandler** in **FBSDKGraphRequestConnection**. 

**Crash Information:**

-[NSNull count]: unrecognized selector sent to instance 0x1c6877ad8'
*** First throw call stack:
(0x1859155f0 0x185637bcc 0x185819ea8 0x185919694 0x18591b5bc 0x1053e46dc 0x1053e8f68 0x1053d16dc 0x1053cf2b4 0x1053cbdb0 0x1053cbbcc 0x1053cb7d0 0x1858e8c7c 0x1857eccdc 0x1053cb224 0x1053ca0c8 0x1053c6fcc 0x1053f8204 0x10594e338 0x10594f730 0x10595d710 0x185893748 0x18588e61c 0x18588dc34 0x18f9d738c 0x1899c022c 0x1049c0278 0x185715800)
libc++abi.dylib: terminating with uncaught exception of type NSException

Hope you help us to solve this problem as soon as possible, thank you very much！

**Comment by iamszabo** [comment] 2020-07-10 10:38
Suddenly we are having the same issue with our app that was working fine before.

```#0	0x000000010cbcac5d in dispatch_async ()
#1	0x0000000107eaeccb in -[FBSDKGraphRequestConnection invokeHandler:error:response:responseData:] at Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/GraphAPI/FBSDKGraphRequestConnection.m:987
#2	0x0000000107eaeab5 in -[FBSDKGraphRequestConnection logAndInvokeHandler:response:responseData:requestStartTime:] at Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/GraphAPI/FBSDKGraphRequestConnection.m:978
#3	0x0000000107eaefce in -[FBSDKGraphRequestConnection taskDidCompleteWithResponse:data:requestStartTime:handler:] at Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/GraphAPI/FBSDKGraphRequestConnection.m:1004
#4	0x0000000107ea6d2c in __36-[FBSDKGraphRequestConnection start]_block_invoke_2 at Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/GraphAPI/FBSDKGraphRequestConnection.m:249
#5	0x00007fff22d9a1f8 in ___lldb_unnamed_symbol246$$CFNetwork ()
```

**Comment by ferico55** [comment] 2020-07-10 10:41
related to #1430 more stack traces there

**Comment by mskalgorepublic** [comment] 2020-07-10 10:42
Yes, they change some responses in the completion handler. Handler expecting some value in count in **FBSDKGraphRequestConnection**

**Comment by Dexterzhao** [comment] 2020-07-10 10:53
wtf fb engineers

**Comment by mrduank** [comment] 2020-07-10 11:10
> wtf fb engineers

Real rubbish, this is the second time this year

**Comment by mrduank** [comment] 2020-07-10 11:11
> Yes, they change some responses in the completion handler. Handler expecting some value in count in **FBSDKGraphRequestConnection**

Do you have a timely solution? I'm really worried

**Comment by rehatkathuria** [comment] 2020-07-10 11:12
If you're reading this, I implore you to _really_ consider whether you need this SDK in your codebase.

**Comment by mrduank** [comment] 2020-07-10 11:18
> 是的，他们在完成处理程序中更改了一些响应。处理程序需要**FBSDKGraphRequestConnection**中的计**数值**

I have integrated it into my app, I need some functions of fb, now the initialization has failed, the app crashes as soon as it is opened

**Comment by kamil-buczel** [comment] 2020-07-10 11:20
> If you're reading this, I implore you to _really_ consider whether you need this SDK in your codebase.

Any suggestions how to implement secure authentication through facebook without it?

**Comment by makomobile** [comment] 2020-07-10 11:23
Any fb fix soon?

**Comment by Salman144017** [comment] 2020-07-10 11:23
It has started working now. I believe they reverted the change.

**Comment by mrduank** [comment] 2020-07-10 11:28
> It has started working now. I believe they reverted the change.

I haven't solved it yet, I'm very anxious

**Comment by mrduank** [comment] 2020-07-10 11:29
> Any fb fix soon?

Not yet

**Comment by olgasaliy** [comment] 2020-07-10 11:30
Lol I have the same issue

**Comment by mrduank** [comment] 2020-07-10 11:34
> Lol I have the same issue

 Lol  we're in the same boat。

**Comment by QualityJohn-TT** [comment] 2020-07-10 11:35
Same.  Here's the crashlog 

`Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1b114180c __exceptionPreprocess + 220
1   libobjc.A.dylib               	0x1b0e69fa4 objc_exception_throw + 55
2   CoreFoundation                	0x1b104536c -[NSObject+ 193388 (NSObject) doesNotRecognizeSelector:] + 139
3   CoreFoundation                	0x1b1145c88 ___forwarding___ + 1323
4   CoreFoundation                	0x1b1147a6c _CF_forwarding_prep_0 + 91
5   APPNAME                       	0x10520658c +[FBSDKEventDeactivationManager updateDeactivatedEvents:] + 18146700 (FBSDKEventDeactivationManager.m:64)
6   APPNAME                       	0x1051b79dc +[FBSDKServerConfigurationManager processLoadRequestResponse:error:appID:] + 17824220 (FBSDKServerConfigurationManager.m:241)
7   APPNAME                       	0x1051b7204 __78+[FBSDKServerConfigurationManager loadServerConfigurationWithCompletionBlock:]_block_invoke + 17822212 (FBSDKServerConfigurationManager.m:163)
8   APPNAME                       	0x105201458 -[FBSDKGraphRequestMetadata invokeCompletionHandlerForConnection:withResults:error:] + 18125912 (FBSDKGraphRequestMetadata.m:41)
9   APPNAME                       	0x10520ad70 __82-[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:]_block_invoke + 18165104 (FBSDKGraphRequestConnection.m:803)
10  APPNAME                       	0x10520ac54 -[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:] + 18164820 (FBSDKGraphRequestConnection.m:837)
11  APPNAME                       	0x10520a804 __64-[FBSDKGraphRequestConnection completeWithResults:networkError:]_block_invoke + 18163716 (FBSDKGraphRequestConnection.m:786)
12  CoreFoundation                	0x1b1114720 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 15
13  CoreFoundation                	0x1b1017ca0 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 191
14  APPNAME                       	0x10520a5a8 -[FBSDKGraphRequestConnection completeWithResults:networkError:] + 18163112 (FBSDKGraphRequestConnection.m:766)
15  APPNAME                       	0x1052098d4 -[FBSDKGraphRequestConnection completeFBSDKURLSessionWithResponse:data:networkError:] + 18159828 (FBSDKGraphRequestConnection.m:631)
16  APPNAME                       	0x10520785c __36-[FBSDKGraphRequestConnection start]_block_invoke_3 + 18151516 (FBSDKGraphRequestConnection.m:241)
17  libdispatch.dylib             	0x1b0e0e610 _dispatch_call_block_and_release + 23
18  libdispatch.dylib             	0x1b0e0f184 _dispatch_client_callout + 15
19  libdispatch.dylib             	0x1b0dc1190 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1043
20  CoreFoundation                	0x1b10bf3a8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 11
21  CoreFoundation                	0x1b10ba39c __CFRunLoopRun + 2003
22  CoreFoundation                	0x1b10b98a0 CFRunLoopRunSpecific + 463
23  GraphicsServices              	0x1bb011328 GSEventRunModal + 103
24  UIKitCore                     	0x1b51aa740 UIApplicationMain + 1935
25  APPNAME                       	0x1040be740 main + 26432 (main.mm:41)
26  libdyld.dylib                 	0x1b0f44360 start + 3
`

**Comment by idealz** [comment] 2020-07-10 11:42
Someone has an update, my app started crashing on launch

**Comment by CleSmartwave** [comment] 2020-07-10 11:47
FF: All our apps are crashing!! Someone with a workaround??

**Comment by idealz** [comment] 2020-07-10 11:49
the crash rate is 10-9, on of the sessions survives - doesn't mean its fixed, it's still crashing, what an ugly show, removing the sdk as soon as this is sorted

**Comment by theemfs** [comment] 2020-07-10 11:59
fb as always...

**Comment by hardW** [comment] 2020-07-10 12:23
For me updating FBSDKLoginKit and FBSDKShareKit to 5.15.1 (was 5.5.0) seem to fix an issue? Please double check

**Comment by diskman86** [comment] 2020-07-10 12:24
Same issue here. Waze and Spotify crash during initialization.

**Comment by niteshborad** [comment] 2020-07-10 12:40
> For me updating FBSDKLoginKit and FBSDKShareKit to 5.15.1 (was 5.5.0) seem to fix an issue. Please double check.

Is it Planned obsolescence to force developers to update the SDK!  🤣
I have already been receiving the warning from them to update the SDK.

**Comment by niteshborad** [comment] 2020-07-10 13:03
**UPDATE**
It looks like issue is resolved from FB backend now. 😌

**Comment by DariDev** [comment] 2020-07-10 13:14
This caused my app to crash like crazy while it was live, how would i prevent something like this from happening in the future ? any suggestion ??

**Comment by hardW** [comment] 2020-07-10 13:17
> This caused my app to crash like crazy while it was live, how would i prevent something like this from happening in the future ? any suggestion ??

Use LaunchDarkly to disable FB SDK?

**Comment by luizmb** [comment] 2020-07-10 13:18
> This caused my app to crash like crazy while it was live, how would i prevent something like this from happening in the future ? any suggestion ??

Please check this thread with some ideas
https://twitter.com/luizguitar/status/1281547854880923649

More specifically this:
https://twitter.com/luizguitar/status/1281571562689310725

**Comment by joesus** [comment] 2020-07-10 16:00
Duplicate of #1427

**Closed by joesus** 2020-07-10 16:00 UTC
