### ISSUE TITLE
Why FacebookCoreKit needs to register exception handler?

### ISSUE THREAD

**Issue by west0r** [facebook/facebook-ios-sdk#1286] opened 2020-03-17 17:58 UTC
I see that FBSDKCrashHandler registers as exception handler inside FacebookCoreKit. It conflicts with our handler and I want to disable it but can't because it's private. Looks suspicious. What for it needs to? And can I disable it without consequences for integration with facebook advertisement library?

**Comment by tianqibt** [comment] 2020-03-19 20:56
Hi @west0r, FBSDKCrashHandler is helping us collect info about the crash caused by Facebook SDK. There are two ways to disable it: 1) you can call the disable function in FBSDKCrashHandler, or 2)you can provide app id, and we will disable the feature for your app on server side.

**Comment by west0r** [comment] 2020-03-20 10:12
I already disabled it using objc runtime. Our app ID is 472292516308756.

**Comment by tianqibt** [comment] 2020-03-20 18:01
Cool! Then I'll close this issue.

**Closed by tianqibt** 2020-03-20 18:01 UTC

**Comment by west0r** [comment] 2020-03-21 11:33
Can you add ability to disable it explicitly?

**Comment by dinesh-hike** [comment] 2022-09-01 12:29
@west0r Please share the code that you used to disable the Facebook exception handler. I am having doubt the Facebook exception handler is conflicting with the Crashlytics exception handler.

**Comment by uzunbe** [comment] 2022-09-01 21:37
The issue seems to be insecure. Please, I want to check on
salma.turk.moda.2022 page. I don't want to lose it and its performance is
weaker. I want a solution to restore its activity 😰😨 👇


https://github.com/west0r
@west0r




♡Amira Hanem♡
♡salma türk modası♡
♡UzunBey♡
