### ISSUE TITLE
Use the 5.0.2 version of the app to start a comprehensive crash

### ISSUE THREAD

**Issue by danbus** [facebook/facebook-ios-sdk#1428] opened 2020-07-10 09:47 UTC
Using the 5.0.2 version of the app, it started to crash from 2020-07-10 06:00:00 (GMT). The error message is as follows. Now all users are affected. The trouble is fixed as soon as possible. Thank you very much!!

Crash information

-[NSNull count]: unrecognized selector sent to instance 0x1cd6fe1e0
2020-07-10 17:24:26.052924+0800 OSDemo[4198:604792] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull count]: unrecognized selector sent to instance 0x1cd6fe1e0'
*** First throw call stack:
(0x18b944300 0x18b658c1c 0x18b842a90 0x18b948a60 0x18b94ad60 0x102e3e8c4 0x102e36e0c 0x102e35a3c 0x102e73ee0 0x102e7cdc4 0x102e7cca8 0x102e7c858 0x18b91667c 0x18b814248 0x102e7c5fc 0x102e7b948 0x102e79930 0x103471d10 0x10347318c 0x103481d14 0x18b8bf6b0 0x18b8ba2c8 0x18b8b98f4 0x195cd0604 0x18fa8d358 0x102a3f1a4 0x18b7352dc)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ferico55** [comment] 2020-07-10 10:42
related to #1430 please help guys!

**Comment by zeqinjie** [comment] 2020-07-11 04:57
me too,  happen
crash  +[FBSDKRestrictiveDataFilterManager updateFilters:] + 96

**Comment by joesus** [comment] 2020-08-03 20:38
Duplicate of  #1430

**Closed by joesus** 2020-08-03 20:38 UTC
