### ISSUE TITLE
FBSdk start crashing at FBSDKRestrictiveDataFilterManager

### ISSUE THREAD

**Issue by Nk-Official** [facebook/facebook-ios-sdk#1432] opened 2020-07-10 11:05 UTC
Suddenly I am facing crash in FBSDKRestrictiveDataFilterManager Line no 62 if (restrictiveParams.count > 0) {

**Comment by Ralph1300** [comment] 2020-07-10 11:08
we also started seeing this now - a lot of crashes happening here.

**Comment by chayansystango** [comment] 2020-07-10 11:10
Crashing everytime the app is launched. This has in fact happened just a month ago as well. https://github.com/facebook/facebook-ios-sdk/issues/1374

**Comment by puppywang** [comment] 2020-07-10 11:10
We face the same issue, a lot of crash, please fix it ASAP.

**Comment by oliver98844** [comment] 2020-07-10 11:11
Same in our app...cannot open Spotify, either

**Comment by nicoyuste** [comment] 2020-07-10 11:12
We have seen the same issue in our app as well. Looks like it was only a big spike but it is still happening.
![Captura de pantalla 2020-07-10 a las 13 02 02](https://user-images.githubusercontent.com/5048526/87148569-eaf14580-c2ae-11ea-9ab8-c3e699a8e8c6.png)

**Comment by mskalgorepublic** [comment] 2020-07-10 11:15
#1430

**Comment by zavsby** [comment] 2020-07-10 11:16
@nicoyuste the soike is not so bug because Firebase crash reporting is down after few minutes, it was the same the last time.

**Comment by redok016** [comment] 2020-07-10 11:18
Rollback please.

**Comment by KevinLaRosa** [comment] 2020-07-10 11:21
We encounter the same issue.

**Comment by yujiea** [comment] 2020-07-10 11:21
We have the same issue. It is crazy.

**Comment by dmydry** [comment] 2020-07-10 11:23
Confirm, ios app is dead

**Comment by Salman144017** [comment] 2020-07-10 11:24
It has started working now. I believe they reverted the change

**Comment by VDetish** [comment] 2020-07-10 11:25
Камон фейсбук, зачем ты пол аппстора убил?

**Comment by alexanderathan** [comment] 2020-07-10 11:25
We have exactly the same issue. Firebase Crashlytics reports that crashes are spiking in the last hour for FBSDKEventDeactivationManager.m.

**Comment by MargaretRawr** [comment] 2020-07-10 11:26
Spotify, Soundcloud and some other major apps have the same instant crash issue it seems..

**Comment by patrikqvarnstrom** [comment] 2020-07-10 11:30
Friday deploy, what's the worst that can happen.

**Comment by gitByEOS** [comment] 2020-07-10 11:32
Happend again

**Comment by gitByEOS** [comment] 2020-07-10 11:41
The crash rate went from 0.2% to 65%.

**Comment by guillaumemeunier** [comment] 2020-07-10 11:41
They never learn...

**Comment by jaydenkieran** [comment] 2020-07-10 11:42
This will be the push that a lot of developers needed to stop using the Facebook SDK in their apps. A remote kill-switch (intentional or not) for apps **running in production** is completely unacceptable and financially damaging for the companies that use it.

**Comment by harshthaker** [comment] 2020-07-10 11:49
It crashes! 
FBSDKRestrictiveDataFilterManager Class - Line 60 is where it breaks!
`-[NSNull count]: unrecognized selector sent to instance 0x1f61521e0`

**Comment by mayur43s** [comment] 2020-07-10 11:49
On line no 68 as well.
![Screenshot 2020-07-10 at 5 18 39 PM](https://user-images.githubusercontent.com/5563481/87151432-711e8380-c2d1-11ea-977a-461bbff4d8d7.png)

**Comment by andproff** [comment] 2020-07-10 12:00
line 66 as well
![Screenshot 2020-07-10 at 2 59 02 PM](https://user-images.githubusercontent.com/1391561/87152233-031c9100-c2be-11ea-9fa6-8a65335d7f55.png)

**Comment by chengssir** [comment] 2020-07-10 12:18
I compared the versions of my two projects，5.11.1 vs 5.6.1，I found that in 5.11.1, 
+ (void)updateFilters:(nullable NSDictionary<NSString *, id> *)restrictiveParams 

Inside the function，have 

if (!isRestrictiveEventFilterEnabled) {
    return;
}

**Comment by houyunpeng** [comment] 2020-07-10 12:41
OMG!  It is CRAZY!!

**Comment by androdev700** [comment] 2020-07-10 12:43
Any updates, when is this gonna get fixed? My app crashes are rising :/

**Comment by AlexUzan** [comment] 2020-07-10 12:45
It seems fixed

**Comment by Bad-Listener** [comment] 2020-07-10 12:51
seems ok for us too!

**Comment by jasonandress** [comment] 2020-07-10 12:55
I wish facebook learned from the last time! I'm 👌 close to removing facebook from my app.

**Comment by redok016** [comment] 2020-07-10 13:26
where is mark?

**Comment by joesus** [comment] 2020-07-10 15:46
Duplicate of #1427

**Closed by joesus** 2020-07-10 15:46 UTC
