### ISSUE TITLE
Facebook application is not opening on clicking "Open facebook application"

### ISSUE THREAD

**Issue by maaviakamran** [facebook/facebook-ios-sdk#1171] opened 2020-01-07 08:23 UTC
Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.3`
- Swift Version: `5.2` (if issue is Swift related)
- Installation Platform & Verison: `[Cocoapods|Carthage|Manual]` version `X.X.X`

## Goals

What do you want to achieve?

## Expected Results

What do you expect to happen?
it should open facebook application
## Actual Results

What actually happened? Can you provide a stack trace?

we have an application "RSVPify" install on iOS devices. when  we click on open facebook app it will drag me to  "RSVPify" that application and facebook not opened at all. can you please fix this in iOS sdk
## Steps to Reproduce

What are the steps necessary to reproduce this issue?

need to download "RSVPify" and click on open with facebook app.

```

**Comment by maaviakamran** [comment] 2020-01-07 08:24
![3528ACD1-3CB5-4AF2-8FEC-4A93B0F447BC](https://user-images.githubusercontent.com/47442536/71879921-04bf9d80-3151-11ea-8e2d-dfcf70a0c74b.jpg)

**Comment by joesus** [comment] 2020-01-20 19:48
Hi, are you able to reproduce this issue in a sample application? There is not enough detail in this issue to provide any help. I am unable to determine if the issue is with the SDK code or the implementation of the SDK code. 

How specifically are you using this? Is this login, sharing, etc...

**Comment by zxt5105515** [comment] 2020-01-21 08:06
RSVpify's fault. this app misuse the URL scheme "fbauth2" in Info.plist file,  "fbauth2" should be in LSApplicationQueriesSchemes , not CFBundleURLTypes

**Comment by joesus** [comment] 2020-01-22 17:21
Closing as it sounds like this issue has been resolved.

**Closed by joesus** 2020-01-22 17:21 UTC

**Comment by crazytom26** [comment] 2020-05-07 06:51
@maaviakamran  Have you solved the problem? I met this too, the open button doesn't respond.

**Comment by Lionwey** [comment] 2020-05-21 12:38
me too..

**Comment by joesus** [comment] 2020-05-21 20:37
Locking conversation because this was resolved for the OP. If you are having the same problem, please open a new issue with a reproducible sample so we can help debug. Thank you.
