### ISSUE TITLE
FBSDKShareDialog (native) invokes delegate didCancel although successfully posted

### ISSUE THREAD

**Issue by Tufals** [facebook/facebook-ios-sdk#773] opened 2015-06-12 07:26 UTC
When showing the share dialog of the native ios app and successfully submitting the post, the delegate didCancel is called instead of didCompleteWithResults. When the native app is not installed and the web browser is used, the callback methods are correctly called. Tested on iphone 4 with iOS 7.1.2.

**Comment by SotoiGhost** [comment] 2015-06-12 16:55
Same problem here, tested on iPhone 6 with iOS 8.3

**Comment by MarceloAmorim** [comment] 2015-06-15 02:56
I have the same issue here... FB guys, please help!

**Comment by chrisp-fb** [comment] 2015-06-18 17:43
Can you post more details like code snippets of are you're invoking the dialog, and what version of the SDK you're using? We have identified an issue where presenting a dialog inside the callback of another dialog or login call can present this symptom which will be fixed in the next release.

**Comment by danielbarrosamorim** [comment] 2015-06-18 18:35
Hi chrisp-fb,

Do you know when the next version with this correction will be release?Or, at least, an estimative.

Thanks

**Comment by chrisp-fb** [comment] 2015-06-18 18:51
We generally release near the end of each month.

**Comment by Tufals** [comment] 2015-06-18 21:32
Hello chrisp-fb,

i've used the newest release (4.2.0) and followed the code presented in the tutorial (https://developers.facebook.com/docs/ios/getting-started).

For sharing i'm using the following code:
//Create content
   FBSDKShareLinkContent *content = [[FBSDKShareLinkContent alloc] init];
    content.contentURL = [NSURL URLWithString:contentURL];
    content.contentDescription =contentDescription;
    content.contentTitle = contentTitle;
    content.imageURL = [NSURL URLWithString:imageURL];
 
//Show the share dialog

[FBSDKShareDialog showFromViewController:self.appDelegate.tealeafViewController                                withContent:content delegate:self];

**Comment by chrisp-fb** [comment] 2015-06-18 21:34
Can you include a sample project that isolates the issue and reproduces it, or modify one of the SDK samples to reproduce it?

**Comment by Tufals** [comment] 2015-06-18 21:41
hi i'll do that tomorrow and report back ...

**Comment by mulp** [comment] 2015-06-21 15:37
Hi,
I got the same problem on sharing an URL on Facebook.

here is my code:
```
- (void)_shareWithFacebook
{
    FBSDKShareLinkContent *content = [[FBSDKShareLinkContent alloc] init];
    content.contentURL = [NSURL URLWithString:@"https://developers.facebook.com/docs/ios/share/"];
    [FBSDKShareDialog showFromViewController:self withContent:content delegate:self];
}

#pragma mark - FBSDKSharingDelegate methods
- (void)sharer:(id<FBSDKSharing>)sharer didCompleteWithResults:(NSDictionary *)results
{
    NSLog(@"Success"):
}

- (void)sharerDidCancel:(id<FBSDKSharing>)sharer
{
    NSLog(@"canceled!");
}

- (void)sharer:(id<FBSDKSharing>)sharer didFailWithError:(NSError *)error
{
    NSLog(@"Fail"):
}
```

the delegate method sharerDidCancel is called even if the post is successfully posted.

Any suggestion ?
Cheers.

**Comment by chrisp-fb** [comment] 2015-06-22 17:02
@mulp  can you link/attach a sample project to demonstrates the problem?

**Comment by mulp** [comment] 2015-06-24 10:10
Hello chrisp-fb,
sorry for the delay...I made some test on my spare time.

I have just realised that the issue was caused by an error on the facebook scheme matched in the method:

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
```

I fixed this issue on the sample project and now it works like a charm. Later I will test it on my app and I will post again (hopefully I won't) only if I'll get some issues again.

For the other guys who are getting the same issue, be sure to add this code in you AppDelegate:

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    
    NSString *FACEBOOK_SCHEME = @"fb_<YOUR_FACEBOOK_APP_ID>";
    if ([[url scheme] isEqualToString:FACEBOOK_SCHEME])
        
        return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                              openURL:url
                                                    sourceApplication:sourceApplication
                                                           annotation:annotation];
    return NO;
}

- (void)applicationDidBecomeActive:(UIApplication *)application
{
    [FBSDKAppEvents activateApp];
}
```

Cheers.

**Comment by Speedy777** [comment] 2015-06-24 10:23
Just want to Rock and Roll

**Comment by Speedy777** [comment] 2015-06-24 10:25
Be sure to check out The I Thought You Wetre Dead Already C/D.Available Now at Best Buys and Walmart

**Comment by chrisp-fb** [comment] 2015-06-24 17:50
@mulp I'm glad you got it working but there shouldn't be any need to check the scheme in your sample. Simply passing it to the FBSDKApplicationDelegate should suffice.

**Closed by chrisp-fb** 2015-06-24 17:50 UTC
