### ISSUE TITLE
FBSDKEventDeactivationManager.m line 64 in [FBSDKEventDeactivationManager updateDeactivatedEvents:]

### ISSUE THREAD

**Issue by Kapil0404** [facebook/facebook-ios-sdk#1433] opened 2020-07-10 11:42 UTC
-[NSNull count]: unrecognized selector sent to instance 0x11646a000
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull count]: unrecognized selector sent to instance 0x11646a000'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001161e002e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x000000011604db20 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000116200f94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00000001161e4dac ___forwarding___ + 1436
	4   CoreFoundation                      0x00000001161e6f38 _CF_forwarding_prep_0 + 120
	5   FBSDKCoreKit                        0x0000000111d3bb48 +[FBSDKEventDeactivationManager updateDeactivatedEvents:] + 104
	6   FBSDKCoreKit                        0x0000000111d80bb1 +[FBSDKServerConfigurationManager processLoadRequestResponse:error:appID:] + 3553
	7   FBSDKCoreKit                        0x0000000111d6058d __69+[FBSDKGraphRequestPiggybackManager addServerConfigurationPiggyback:]_block_invoke + 157
	8   FBSDKCoreKit                        0x0000000111d5dd74 -[FBSDKGraphRequestMetadata invokeCompletionHandlerForConnection:withResults:error:] + 212
	9   FBSDKCoreKit                        0x0000000111d59974 __82-[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:]_block_invoke + 212
	10  FBSDKCoreKit                        0x0000000111d597b5 -[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:] + 1077
	11  FBSDKCoreKit                        0x0000000111d592e4 __64-[FBSDKGraphRequestConnection completeWithResults:networkError:]_block_invoke + 1332
	12  CoreFoundation                      0x00000001161adf97 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	13  CoreFoundation                      0x00000001160f3584 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 228
	14  FBSDKCoreKit                        0x0000000111d58c68 -[FBSDKGraphRequestConnection completeWithResults:networkError:] + 1048
	15  FBSDKCoreKit                        0x0000000111d57880 -[FBSDKGraphRequestConnection completeFBSDKURLSessionWithResponse:data:networkError:] + 2112
	16  FBSDKCoreKit                        0x0000000111d542c8 __36-[FBSDKGraphRequestConnection start]_block_invoke_3 + 168
	17  FBSDKCoreKit                        0x0000000111d5b924 __73-[FBSDKGraphRequestConnection invokeHandler:error:response:responseData:]_block_invoke + 52
	18  libdispatch.dylib                   0x0000000117c2add4 _dispatch_call_block_and_release + 12
	19  libdispatch.dylib                   0x0000000117c2bd48 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x0000000117c39de6 _dispatch_main_queue_callback_4CF + 1500
	21  CoreFoundation                      0x0000000116142df9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x000000011613da59 __CFRunLoopRun + 2329
	23  CoreFoundation                      0x000000011613ce16 CFRunLoopRunSpecific + 438
	24  GraphicsServices                    0x000000011862fbb0 GSEventRunModal + 65
	25  UIKitCore                           0x0000000126dd5b48 UIApplicationMain + 1621
	26  E.ON                                0x000000010df19791 main + 193
	27  libdyld.dylib                       0x0000000117cb3c25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by puppywang** [comment] 2020-07-10 11:44
Duplicate #1430

**Comment by MauriceArikoglu** [comment] 2020-07-10 12:29
Happens for us as well. This is crashing a production application on launch. Not cool.

**Comment by 08031992** [comment] 2020-07-10 13:20
it crashing a lot . please rollback the code of SDK .
our application need to be stable for production.

**Comment by joesus** [comment] 2020-07-10 15:46
Duplicate of #1427

**Closed by joesus** 2020-07-10 15:46 UTC
