### ISSUE TITLE
Feature Request: Dismiss ShareDialog after a content has been shared

### ISSUE THREAD

**Issue by Knapiii** [facebook/facebook-ios-sdk#2112] opened 2022-09-05 09:29 UTC
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)

### Goals

After a content is shared with Facebook, the share pop up view will be dismissed

### Expected results

Dismiss the `ShareDialog` after the content has been shared with Facebook

### Code samples & details

```swift
// INSERT YOUR CODE HERE
let content = ShareLinkContent()
let showDialog = ShareDialog(viewController: presenter, content: content, delegate: self)
if (showDialog.canShow) {
   showDialog.show()
}
```

**Comment by kross51** [comment] 2022-09-07 05:48
I have the same issue in iOS 15/16 on any of my iDevices.  After sharing to Facebook with FBSDKShareDialogModeShareSheet the "Shared to Facebook!" confirmation shows but there is no way to dismiss.  Also, delegates never get called for success (even though I see post to my Facebook test account).  Please remedy; I don't know how everyone isn't complaining about this as it cripples the app so nothing else can be done!

**Comment by chuochuodashenjing** [comment] 2022-09-07 06:27
I had the same problem

    FBSDKSharePhoto * sharePhoto = [[FBSDKSharePhoto alloc] initWithImage:uiImage isUserGenerated:YES];
    FBSDKSharePhotoContent* content = [[FBSDKSharePhotoContent alloc] init];
    content.photos = @[sharePhoto];
    [FBSDKShareDialog showFromViewController:[IZLAuthon currentViewController] withContent:content delegate:self];

![1341662358102_ pic](https://user-images.githubusercontent.com/14501720/188804303-46980f08-b97b-472c-9110-
2bd182bc6026.jpg)

**Comment by chuochuodashenjing** [comment] 2022-09-07 06:28
![WechatIMG134](https://user-images.githubusercontent.com/14501720/188804658-7aea405c-49fd-4efa-a053-089ead6d00cf.jpeg)
I had the same problem

    FBSDKSharePhoto * sharePhoto = [[FBSDKSharePhoto alloc] initWithImage:uiImage isUserGenerated:YES];
    
    FBSDKSharePhotoContent* content = [[FBSDKSharePhotoContent alloc] init];
    content.photos = @[sharePhoto];
        
    [FBSDKShareDialog showFromViewController:[IZLAuthon currentViewController] withContent:content delegate:self];

**Comment by QIYA0130** [comment] 2022-09-07 07:02
same issue，using 14.1.0 version SDK

**Comment by Rycccccccc** [comment] 2022-09-07 08:56
我也遇到了这样的问题，

**Comment by yingguqing** [comment] 2022-09-07 09:55
I have the same issue。

**Comment by lixiang1994** [comment] 2022-09-08 03:23
+1

**Comment by ArsalImam** [comment] 2022-09-08 09:36
I did some hypotheses on this, I think it is a bug related to the Facebook App. Details are mentioned on #2114

**Comment by mhchoi-bagelcode** [comment] 2022-09-08 14:46
+1

**Comment by Forrest-Ripl** [comment] 2022-09-08 20:59
+1

**Comment by pratik-softgames** [comment] 2022-09-09 09:31
I have the same issue

**Comment by ankitpunchh** [comment] 2022-09-11 10:05
Any update facing the same issue.

**Comment by Polenoso** [comment] 2022-09-12 13:55
Same here, delegate is never being called after using DialogMode `shareSheet` it just works when using `native` mode.

I can' even dismiss the SLComposeViewController created by the SDK, it blocks our App once displayed.

**Comment by ArsalImam** [comment] 2022-09-12 16:12
The issue is in Facebook app which is fixed already and will be released in v383. Please refer the issue details in #2114

**Comment by ankitpunchh** [comment] 2022-09-13 08:27
It is available now in the new release: https://github.com/facebook/facebook-ios-sdk/issues/2114#issuecomment-1244843458

**Comment by samodom** [comment] 2022-09-20 21:48
Closing as fixed per #2114

**Closed by samodom** 2022-09-20 21:48 UTC
Labels: enhancement, needs-triage

**Comment by uzunbe** [comment] 2022-09-21 10:35
؟؟

**Comment by uzunbe** [comment] 2022-09-21 10:46
🙋‍♂️تم الإرسال من Galaxy الخاص بي
-------- الرسالة الأصلية --------من: "salma turk.moda.2022" ***@***.***> التاريخ: ٢١‏/٩‏/٢٠٢٢  ١:٣٥ م  (GMT+03:00) إلى: facebook/facebook-ios-sdk ***@***.***> نسخة: "salma turk.moda.2022" ***@***.***>, Your activity ***@***.***> الموضوع: Re: [facebook/facebook-ios-sdk] Feature Request: Dismiss ShareDialog after a content has been shared (Issue #2112) 

؟؟

**Comment by uzunbe** [comment] 2022-09-21 11:58
تم الإرسال من Galaxy الخاص بي
-------- الرسالة الأصلية --------من: "salma turk.moda.2022" ***@***.***> التاريخ: ٢١‏/٩‏/٢٠٢٢  ١:٤٦ م  (GMT+03:00) إلى: facebook/facebook-ios-sdk ***@***.***> نسخة: "salma turk.moda.2022" ***@***.***>, Your activity ***@***.***> الموضوع: Re: [facebook/facebook-ios-sdk] Feature Request: Dismiss ShareDialog after a content has been shared (Issue #2112) 

🙋‍♂️تم الإرسال من Galaxy الخاص بي

-------- الرسالة الأصلية --------من: "salma turk.moda.2022" ***@***.***> التاريخ: ٢١‏/٩‏/٢٠٢٢  ١:٣٥ م  (GMT+03:00) إلى: facebook/facebook-ios-sdk ***@***.***> نسخة: "salma turk.moda.2022" ***@***.***>, Your activity ***@***.***> الموضوع: Re: [facebook/facebook-ios-sdk] Feature Request: Dismiss ShareDialog after a content has been shared (Issue #2112) 



؟؟
