### ISSUE TITLE
Build fails on Travis while fastlane scan

### ISSUE THREAD

**Issue by poorvasingh04** [facebook/facebook-ios-sdk#1644] opened 2021-02-09 10:40 UTC
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version:  12.3
- Swift Version: `5`
- Installation Platform & Verison: `Cocoapods` version `1.10.1`
- (FBSDKCoreKit & FBSDKLoginKit) v `9.0.0`

## Goals

We have iOS project running in travis and it was working fine until now. We recently upgraded Facebook framework (FBSDKCoreKit & FBSDKLoginKit) to v 9.0.0 and it started failing. Though everything works on our local machine, it fails in travis. 

## Expected Results

Everything works on local machine. It should work with fastlane as well.

## Actual Results

It runs fastlane scan command which fails with following error at the end:

*.app (25046) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying Error: Test crashed with signal ill before starting test execution.

## Steps to Reproduce

Update (FBSDKCoreKit & FBSDKLoginKit) to v 9.0.0 and build with fastlane scan

**Comment by joesus** [comment] 2021-02-10 17:36
Not very familiar with fastlane scan. Without more logs it's basically impossible to say what's failing or why... 

You can try to reproduce with a simple sample to see if it's something related to your specific project configuration, or try to find more detailed output. Closing for now since I don't see a way to help. Please open a more detailed issue when there is more information to use for debugging. Thanks!

**Closed by joesus** 2021-02-10 17:36 UTC

**Comment by poorvasingh04** [comment] 2021-02-12 17:10
I updated fb sdk from 9.0.0 to 9.0.1 and now it works fine.
